# Generated by Django 4.0.3 on 2022-03-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
