# Generated by Django 4.0.3 on 2022-03-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0004_passport_test_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
