# Generated by Django 4.0.3 on 2022-03-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0009_rename_user_id_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.user'),
        ),
    ]
