# Generated by Django 4.0.3 on 2022-03-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0010_alter_vaccine_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='user_id',
            new_name='user',
        ),
    ]
