# Generated by Django 4.0.3 on 2022-03-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0012_alter_passport_user_id_alter_passport_vaccine_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='passport',
            old_name='vaccine_id',
            new_name='vaccine',
        ),
    ]
