# Generated by Django 4.0.3 on 2022-03-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0013_rename_user_id_passport_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='name',
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='date',
            field=models.DateTimeField(verbose_name='date of vaccination'),
        ),
    ]
