# Generated by Django 4.0.3 on 2022-03-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0015_alter_test_date_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Files',
        ),
    ]
