# Generated by Django 4.0.3 on 2022-03-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0017_rename_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(upload_to='files/'),
        ),
    ]
