# Generated by Django 4.0.3 on 2022-03-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0018_alter_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
